cvs up -r 1.3 usb4rexx/Usb4Rexx.c
cvs up -r 1.3 usb4rexx/Usb4Rexx.def
cvs up -r 1.5 usb4rexx/Usb4Rexx.dll
cvs up -r 1.1 usb4rexx/Usb4Rexx.txt
cvs up -r 1.1 usb4rexx/global.h 
cvs up -r 1.1 usb4rexx/globaldefs.h
cvs up -r 1.1 usb4rexx/globrexx.c
cvs up -r 1.1 usb4rexx/globrexx.h
cvs up -r 1.2 usb4rexx/globstr.c
cvs up -r 1.1 usb4rexx/globstr.h
cvs up -r 1.1 usb4rexx/make.cmd
cvs up -r 1.1 usb4rexx/testrexx.cmd
cvs up -r 1.3 usb4rexx/examples/CasioWMP.cmd
cvs up -r 1.3 usb4rexx/examples/mmport.cmd
